require 'firewatir'
include FireWatir
ff = Firefox.new

ff.goto('http://mail.google.com/mail/h/yonrmu0x2vb7/?zy=f&f=1')
raise "page title doesn't match" unless ff.title == 'Gmail - Posteingang'
ff.element_by_xpath('//TABLE[3]/TBODY[1]/TR[1]/TD[1]/TABLE[2]/TBODY[1]/TR[1]/TD[1]/*/A[@CDATA=\"greader\"]').click
raise "page title doesn't match" unless ff.title == 'Gmail - Label: greader'
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@TYPE=\"checkbox\" and @NAME=\"t\"]').set
ff.element_by_xpath('//FORM[@NAME=\"f\"]/*/INPUT[@NAME=\"nvp_tbu_go\" and @VALUE=\"Start\"]').click
raise "page title doesn't match" unless ff.title == 'Gmail - Label: greader'

